Day-3/Exercise-Auctions-site/auction_site/config/routes.rb
Rails.application.routes.draw do
  get 'bids/create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'users' => 'users#index'
  post 'users' => 'users#create'
  get 'users/new' => 'users#new', as: 'user_new'
  get 'users/:id/edit' => 'users#edit', as: 'user_edit'
  get 'users/:id' => 'users#show', as: 'user'
  put 'users/:id' => 'users#update'
  patch 'users/:id' => 'users#update'
  delete 'users/:id' => 'users#destroy'

  get 'products' => 'products#index'
  post 'products' => 'products#create'
  get 'products/new' => 'products#new', as: 'product_new'
  get 'products/:id/edit' => 'products#edit', as: 'product_edit'
  get 'products/:id' => 'products#show', as: 'product'
  put 'products/:id' => 'products#update'
  patch 'products/:id' => 'products#update'
  delete 'products/:id' => 'products#destroy'

  get 'bids' => 'bids#index'
  post 'bids' => 'bids#create'
  get 'bids/new' => 'bids#new', as: 'bid_new'
  get 'bids/:id/edit' => 'bids#edit', as: 'bid_edit'
  get 'bids/:id' => 'bids#show', as: 'bid'
  put 'bids/:id' => 'bids#update'
  patch 'bids/:id' => 'bids#update'
  delete 'bids/:id' => 'bids#destroy'

  root 'users#index'
end

Day-3/Exercise-Auctions-site/auction_site/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Day-3/Exercise-Auctions-site/auction_site/app/models/bid.rb
class Bid < ApplicationRecord
  include ActiveModel::Validations

  belongs_to :user
  belongs_to :product

  validates :amount, numericality: true
  validate :user_cannot_bid_on_their_own_product,
           :amount_must_be_greater_than

  def self.winning_bidder product_id
    max_amount = select(["product_id, MAX(amount) amount"])
    .where(product_id: product_id)
    .to_sql

    min_updated_at = ("SELECT derb_amount.product_id,
                              derb_amount.amount,
                              MIN(bids.updated_at) updated_at
                      FROM (#{max_amount}) derb_amount
                        INNER JOIN bids ON bids.product_id = derb_amount.product_id AND
                                           bids.amount = derb_amount.amount")

    bid_where = "bids.product_id = derb.product_id AND
                 bids.amount = derb.amount AND
                 bids.updated_at = derb.updated_at"

    joins("INNER JOIN (#{min_updated_at}) derb")
    .where(bid_where)
    .ids
  end

  private

  def find_product
    Product.find product_id
  end

  def user_cannot_bid_on_their_own_product
    if user_id == find_product.user.id
      errors.add(:user_id, 'Can\'t bid on their own product')
    end
  end

  def amount_must_be_greater_than
    minimum_amount = find_product.calculate_minimum_amount
    if amount.nil? || amount <= minimum_amount
      errors.add(:amount, "must be greater than #{minimum_amount}")
    end
  end
end

Day-3/Exercise-Auctions-site/auction_site/app/models/product.rb
class Product < ApplicationRecord
  has_many :bids
  has_many :users, through: :bids
  belongs_to :user

  validates :title, :deadline, presence: true
  validates :minimum_amount, :numericality => { :greater_than_or_equal_to => 0 }

  def can_new_bids?
    deadline >= Date.today
  end

  def calculate_minimum_amount
    min_amount = minimum_amount || 0
    max_amount_bid = bids.maximum(:amount) || min_amount
    [min_amount, max_amount_bid].max
  end
end

Day-3/Exercise-Auctions-site/auction_site/app/models/user.rb
class User < ApplicationRecord
  has_many :bids
  has_many :products, through: :bids

  validates :name, :email, presence: true
end

Day-3/Exercise-Auctions-site/auction_site/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

Day-3/Exercise-Auctions-site/auction_site/app/controllers/bids_controller.rb
class BidsController < ApplicationController
  def create
    @user = User.find_by_email params[:user_email]
    @bid_new = Bid.new bid_params
    @product = Product.find @bid_new.product_id
    @bid_new.user_id = @user.id unless @user.nil?
    if @bid_new.save
      redirect_to product_path @bid_new.product_id
    else
      @can_new_bids = @product.can_new_bids?
      @bids = @product.bids
      @min_amount = @product.calculate_minimum_amount
      render 'products/show'
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def bid_params
      params.require(:bid).permit(:product_id,
                                  :amount)
    end
end

Day-3/Exercise-Auctions-site/auction_site/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.all
    @products_count = @products.count
  end

  def show
    product_id = @product.id
    @can_new_bids = @product.can_new_bids?
    @winning_bidder = Bid.winning_bidder product_id if !@can_new_bids
    @bids = @product.bids
    @min_amount = @product.calculate_minimum_amount
    @bid_new = Bid.new
    @bid_new.amount = @min_amount
  end

  def edit
  end

  def create
    @product = Product.new product_params
    if @product.save
      redirect_to product_path @product
    else
      render :new
    end
  end

  def update
    if @product.update product_params
      redirect_to product_path
    else
      render :edit
    end
  end

  def destroy
  end

  def new
    @product = Product.new
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find params[:id]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title,
                                      :description,
                                      :deadline,
                                      :minimum_amount,
                                      :user_id)
    end
end

Day-3/Exercise-Auctions-site/auction_site/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
    @users_count = @users.count
  end

  def create
    @user = User.new user_params
    if @user.save
      redirect_to users_path
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      render :show
    else
      render :edit
    end
  end

  def destroy
  end

  def new
    @user = User.new
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name,
                                   :email)
    end
end

Day-3/Exercise-Auctions-site/auction_site/app/helpers/application_helper.rb
module ApplicationHelper
end

Day-3/Exercise-Auctions-site/auction_site/app/helpers/bids_helper.rb
module BidsHelper
end

Day-3/Exercise-Auctions-site/auction_site/app/helpers/products_helper.rb
module ProductsHelper
end

Day-3/Exercise-Auctions-site/auction_site/app/helpers/users_helper.rb
module UsersHelper
end

Day-3/Exercise-Auctions-site/auction_site/app/views/products/_form.html.erb
<%= form_for(product) do |p| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= p.label :title %>
    <%= p.text_field :title %>
  </div>
  <br>
  <div class="field">
    <%= p.label :description %>
    <%= p.text_area :description, cols: 35, rows: 6 %>
  </div>
  <br>
  <div class="field">
    <%= p.label :deadline %>
    <%= p.date_field :deadline %>
  </div>
  <br>
  <div class="field">
    <%= p.label :minimum_amount %>
    <%= p.number_field :minimum_amount, :class => 'text_field', :step => 'any' %>
  </div>
  <br>
  <div class="field">
    <%= p.label :user %>
    <%= p.select :user_id, User.all.collect{ |u| [u.name, u.id] } %>
  </div>
  <br>
  <div class="actions">
    <%= p.submit %>
  </div>
<% end %>

Day-3/Exercise-Auctions-site/auction_site/app/views/products/create.html.erb
<h1>Products#create</h1>
<p>Find me in app/views/products/create.html.erb</p>

Day-3/Exercise-Auctions-site/auction_site/app/views/products/destroy.html.erb
<h1>Products#destroy</h1>
<p>Find me in app/views/products/destroy.html.erb</p>

Day-3/Exercise-Auctions-site/auction_site/app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= render 'form', product: @product %>

Day-3/Exercise-Auctions-site/auction_site/app/views/products/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Products (<%= @products_count %>)</h1>
<%= link_to 'New Product', product_new_path %>
<br><br>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Deadline</th>
      <th>Minimum amount</th>
      <th>UserName</th>
      <th>Bids</th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= link_to product.title, product_path(product) %></td>
        <td><%= link_to product.description, product_edit_path(product) %></td>
        <td><%= product.deadline %></td>
        <td><%= product.minimum_amount %></td>
        <td><%= product.user.name %></td>
        <td><%= product.bids.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

Day-3/Exercise-Auctions-site/auction_site/app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

Day-3/Exercise-Auctions-site/auction_site/app/views/products/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Show Product</h1>
<%= link_to 'Edit', product_edit_path(@product) %>
<p>
    <strong>Title:</strong>
    <%= @product.title %>
</p>
<p>
    <strong>Description:</strong>
    <%= @product.description %>
</p>
<p>
    <strong>Deadline:</strong>
    <%= @product.deadline %>
</p>
<p>
    <strong>Minimum amount:</strong>
    <%= @product.minimum_amount %>
</p>
<p>
    <strong>User:</strong>
    <%= @product.user.name %>
</p>

<% if @can_new_bids %>
  <%= render 'bids/form', bid_new: @bid_new %>
<% end %>
<%= render 'bids/index', bids: @bids %>