Day-2/Exercise-Address-Book/address_book/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'contacts' => 'contacts#index'
  post 'contacts' => 'contacts#create'
  get 'contacts/new' => 'contacts#new', as: 'contact_new'
  get 'contacts/:id' => 'contacts#show', as: 'contact'
  root 'contacts#index'
end

Day-2/Exercise-Address-Book/address_book/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Day-2/Exercise-Address-Book/address_book/app/models/contact.rb
class Contact < ApplicationRecord
    validates :name, :address, presence: true
end

Day-2/Exercise-Address-Book/address_book/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

Day-2/Exercise-Address-Book/address_book/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @contacts = Contact.order(:name)
    @contacts_count = @contacts.count
  end

  def show
    @contact = Contact.find_by(id: params[:id])
  end

  def new

  end

  def create
    contact = Contact.new(
        :name => params[:contact][:name],
        :address => params[:contact][:address],
        :phone => params[:contact][:phone],
        :email => params[:contact][:email]
    )
    contact.save
    redirect_to root_path
  end
end

Day-2/Exercise-Address-Book/address_book/app/helpers/application_helper.rb
module ApplicationHelper
end

Day-2/Exercise-Address-Book/address_book/app/helpers/contacts_helper.rb
module ContactsHelper
end

Day-2/Exercise-Address-Book/address_book/app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Contacts (<%= @contacts_count %>)</h1>
<%= link_to 'New Contact', contact_new_path %>
<br><br>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
    </tr>
  </thead>
  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= link_to contact.name, contact_path(contact) %></td>
        <td><%= contact.email %></td>
      </tr>
    <% end %>
  </tbody>
</table>

Day-2/Exercise-Address-Book/address_book/app/views/contacts/new.html.erb
<h1>Add a new contact</h1>
<form action='/contacts' method='post'>
    <div>
        <label for='contact_name'>Name</label>
        <input type='text' name='contact[name]' id='contact_name'>
    </div>
    <br>
    <div>
        <label for='contact_address'>Address</label>
        <textarea name='contact[address]' id='contact_address'></textarea>
    </div>
    <br>
    <div>
        <label for='contact_phone'>Phone number</label>
        <input type='tel' name='contact[phone]' id='contact_phone'>
    </div>
    <br>
    <div>
        <label for='contact_email'>Email</label>
        <input type='email' name='contact[email]' id='contact_email'>
    </div>
    <br>
    <button type='submit'>Add this contact</button>
    <input type='hidden' name='authenticity_token' value='<%= form_authenticity_token %>'>
</form>
<br>
<%= link_to 'Contact list', root_path %>

Day-2/Exercise-Address-Book/address_book/app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Show Contact</h1>
<p>
    <strong>Name:</strong>
    <%= @contact.name %>
</p>
<p>
    <strong>Address:</strong>
    <%= @contact.address %>
</p>
<p>
    <strong>Phone:</strong>
    <%= @contact.phone %>
</p>
<p>
    <strong>Email:</strong>
    <%= @contact.email %>
</p>
<%= link_to 'Contact list', root_path %>

Day-2/Exercise-Address-Book/address_book/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AddressBook</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>