Day-2/varios/twotter/config/routes.rb
Rails.application.routes.draw do
    resources :users
    resources :twots
    root 'twots#index'
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Day-2/varios/twotter/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Day-2/varios/twotter/app/models/twot.rb
class Twot < ApplicationRecord
    validates :body, presence: true
end

Day-2/varios/twotter/app/models/user.rb
class User < ApplicationRecord
    validates :name, presence: true
    validates :username, format: { with: /\A[a-zA-Z0-9]+\Z/, message: 'can\'t contain white spaces'}
end

Day-2/varios/twotter/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

Day-2/varios/twotter/app/controllers/twots_controller.rb
class TwotsController < ApplicationController
  before_action :set_twot, only: [:show, :edit, :update, :destroy]

  # GET /twots
  # GET /twots.json
  def index
    @twots = Twot.all
  end

  # GET /twots/1
  # GET /twots/1.json
  def show
  end

  # GET /twots/new
  def new
    @twot = Twot.new
  end

  # GET /twots/1/edit
  def edit
  end

  # POST /twots
  # POST /twots.json
  def create
    @twot = Twot.new(twot_params)

    respond_to do |format|
      if @twot.save
        format.html { redirect_to @twot, notice: 'Twot was successfully created.' }
        format.json { render :show, status: :created, location: @twot }
      else
        format.html { render :new }
        format.json { render json: @twot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /twots/1
  # PATCH/PUT /twots/1.json
  def update
    respond_to do |format|
      if @twot.update(twot_params)
        format.html { redirect_to @twot, notice: 'Twot was successfully updated.' }
        format.json { render :show, status: :ok, location: @twot }
      else
        format.html { render :edit }
        format.json { render json: @twot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /twots/1
  # DELETE /twots/1.json
  def destroy
    @twot.destroy
    respond_to do |format|
      format.html { redirect_to twots_url, notice: 'Twot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_twot
      @twot = Twot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def twot_params
      params.require(:twot).permit(:body)
    end
end

Day-2/varios/twotter/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :username, :email, :bio)
    end
end

Day-2/varios/twotter/app/helpers/application_helper.rb
module ApplicationHelper
end

Day-2/varios/twotter/app/helpers/twots_helper.rb
module TwotsHelper
end

Day-2/varios/twotter/app/helpers/users_helper.rb
module UsersHelper
end

Day-2/varios/twotter/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twotter</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

Day-2/varios/twotter/app/views/twots/_form.html.erb
<%= form_for(twot) do |f| %>
  <% if twot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(twot.errors.count, "error") %> prohibited this twot from being saved:</h2>

      <ul>
      <% twot.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_field :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Day-2/varios/twotter/app/views/twots/edit.html.erb
<h1>Editing Twot</h1>

<%= render 'form', twot: @twot %>

<%= link_to 'Show', @twot %> |
<%= link_to 'Back', twots_path %>

Day-2/varios/twotter/app/views/twots/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Twots</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @twots.each do |twot| %>
      <tr>
        <td><%= twot.body %></td>
        <td><%= link_to 'Show', twot %></td>
        <td><%= link_to 'Edit', edit_twot_path(twot) %></td>
        <td><%= link_to 'Destroy', twot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Twot', new_twot_path %>

Day-2/varios/twotter/app/views/twots/new.html.erb
<h1>New Twot</h1>

<%= render 'form', twot: @twot %>

<%= link_to 'Back', twots_path %>

Day-2/varios/twotter/app/views/twots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @twot.body %>
</p>

<%= link_to 'Edit', edit_twot_path(@twot) %> |
<%= link_to 'Back', twots_path %>

Day-2/varios/twotter/app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :bio %>
    <%= f.text_field :bio %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Day-2/varios/twotter/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

Day-2/varios/twotter/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Username</th>
      <th>Email</th>
      <th>Bio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= user.bio %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

Day-2/varios/twotter/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

Day-2/varios/twotter/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @user.bio %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>